/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Plex's global discover catalog for movies and TV shows.
         * @description Uses the Plex account token to query metadata.provider.plex.tv.
         */
        get: operations["discover_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{guid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get media details by GUID across all servers.
         * @description Aggregates the same title from every server (by GUID). Returns versions and availability per server.
         */
        get: operations["get_media_details_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List media requests (pending and/or fulfilled), optionally filtered and sorted by date. */
        get: operations["get_all_requests_handler"];
        put?: never;
        /**
         * Create or update a media request.
         * @description On conflict with an existing pending request for the same (username, guid), merges seasons and updates resolution.
         */
        post: operations["create_request_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/media/{guid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active requests for a specific media guid. */
        get: operations["get_active_requests_by_guid_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove the current user from a request (same as unsubscribe). Deletes the request if no subscribers remain. */
        delete: operations["delete_request_handler"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full-text search over the catalog.
         * @description Searches movies and shows by title/summary. Returns matching items with server and metadata from the catalog.
         */
        get: operations["search_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all Plex servers known to the catalog.
         * @description Each server includes "status" / "statusSince" (see "server_status" module).
         */
        get: operations["get_servers_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers/{server_id}/image/{image_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Proxy or resize an image from a Plex server.
         * @description Images are cached. Optional "width" and "height" query params trigger transcoding to that size.
         */
        get: operations["get_image_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers/{server_id}/items/{rating_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get full metadata for a single item.
         * @description Fetches live from the catalog. Includes media parts and streams. Use rating_key from list/children responses.
         */
        get: operations["get_item_details_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers/{server_id}/items/{rating_key}/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List child items of a media item.
         * @description Fetches from the catalog. For a show returns seasons; for a season returns episodes. Used to build the browse tree.
         */
        get: operations["get_item_children_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers/{server_id}/items/{rating_key}/extras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List bonus features (extras) for a media item.
         * @description Returns extras from the catalog (e.g. trailers, behind-the-scenes). Parent can be a movie, show, season, or episode.
         */
        get: operations["get_item_extras_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers/{server_id}/libraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List libraries (sections) for a server.
         * @description Returns movie/show libraries for the given server ID from the catalog.
         */
        get: operations["get_libraries_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers/{server_id}/libraries/{library_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List top-level items in a library.
         * @description Returns movies and shows in the given library section. Use children or details endpoints to get more information.
         */
        get: operations["get_library_items_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers/{server_id}/seasons/{season_id}/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List episodes for a season.
         * @description Returns episodes from the catalog with resolution and subtitle info. Season_id can be a season rating key or the show rating key when there are no seasons (like a mini-series)
         */
        get: operations["get_episodes_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers/{server_id}/shows/{show_id}/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List seasons for a show.
         * @description Returns seasons from the catalog. If the show has no seasons, may return a single virtual season with all episodes.
         */
        get: operations["get_seasons_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get system and sync health information.
         * @description Returns counts of movies and shows, server counts, last sync time, sync interval, last error (if any), and whether a sync is in progress.
         */
        get: operations["get_system_info_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DbServer: {
            accessToken: string;
            connectionUri: string;
            id: string;
            lastSeen: string;
            /** @description Server name/nickname */
            name: string;
            /** @description Plex owner username (Plex's "sourceTitle") */
            ownerUsername?: string | null;
            /**
             * Format: int32
             * @description Availability: 0 = online, 1 = unreachable, 2 = timeout, 3 = tls, 4 = no connection, 5 = http error
             */
            status: number;
            /** @description When the current non-online status began; null while online */
            statusSince?: string | null;
        };
        DiscoverResultsPage: {
            items: Record<string, never>[];
            /** Format: int64 */
            limit: number;
            /** Format: int64 */
            offset: number;
            /** Format: int64 */
            total: number;
        };
        EpisodeDetails: {
            contentRating?: string | null;
            /** Format: int64 */
            duration?: number | null;
            id: string;
            /** Format: int32 */
            index?: number | null;
            summary?: string | null;
            thumbPath?: string | null;
            title: string;
            versions: components["schemas"]["MediaVersion"][];
        };
        ImageQuery: {
            /** Format: int32 */
            height?: number | null;
            /** Format: int32 */
            width?: number | null;
        };
        /** @description Plex library item (movie, show, episode, extra, etc) */
        Item: {
            Media?: components["schemas"]["Media"][];
            art?: string | null;
            contentRating?: string | null;
            /** Format: int64 */
            duration?: number | null;
            /** @description Plex extra type (e.g. "trailer", "behindTheScenes") when item_type is "extra" */
            extraType?: string | null;
            guid?: string | null;
            /** Format: int32 */
            index?: number | null;
            key: string;
            /** Format: int32 */
            leafCount?: number | null;
            originallyAvailableAt?: string | null;
            parentRatingKey?: string | null;
            ratingKey: string;
            studio?: string | null;
            summary?: string | null;
            thumb?: string | null;
            title: string;
            type: string;
            /** Format: int64 */
            updatedAt?: number | null;
            /** Format: int32 */
            year?: number;
        };
        ItemList: {
            Metadata: components["schemas"]["Item"][];
        };
        ItemWithDetails: {
            Media?: components["schemas"]["Media"][];
            art?: string | null;
            contentRating?: string | null;
            /** Format: int64 */
            duration?: number | null;
            guid?: string | null;
            /** Format: int32 */
            index?: number | null;
            key: string;
            /** Format: int32 */
            leafCount?: number | null;
            originallyAvailableAt?: string | null;
            parentRatingKey?: string | null;
            ratingKey: string;
            studio?: string | null;
            summary?: string | null;
            thumb?: string | null;
            title: string;
            type: string;
            /** Format: int64 */
            updatedAt?: number | null;
            /** Format: int32 */
            year?: number;
        };
        /** @description Plex library section (movies, shows, etc) */
        Library: {
            key: string;
            title: string;
            type: string;
        };
        LibraryItemsPage: {
            items: components["schemas"]["Item"][];
            /** Format: int64 */
            limit: number;
            /** Format: int64 */
            offset: number;
            /** Format: int64 */
            total: number;
        };
        LibraryItemsQuery: {
            /** Format: int32 */
            limit?: number | null;
            /** Format: int32 */
            offset?: number | null;
        };
        Media: {
            Part?: components["schemas"]["Part"][];
            videoResolution?: string | null;
        };
        MediaDetails: {
            artPath?: string | null;
            availableOn: components["schemas"]["ServerAvailability"][];
            contentRating?: string | null;
            /** Format: int64 */
            duration?: number | null;
            guid: string;
            itemType: string;
            originallyAvailableAt?: string | null;
            summary?: string | null;
            thumbPath?: string | null;
            title: string;
            /** Format: int32 */
            year?: number | null;
        };
        /** @description Media request from the database */
        MediaRequest: {
            createdAt: string;
            /** Format: int64 */
            duration?: number | null;
            fulfilledAt?: string | null;
            guid: string;
            /** Format: int32 */
            id: number;
            isUpgrade: boolean;
            isViewed: boolean;
            itemType: string;
            requestedResolution?: string | null;
            /** Format: int32 */
            requestedSeason?: number | null;
            serverNames?: string[] | null;
            status: string;
            subscribers: string[];
            thumb?: string | null;
            title: string;
            updatedAt: string;
            /** Format: int32 */
            year?: number | null;
        };
        /** @description Payload for creating/updating a media request. */
        MediaRequestPayload: {
            /** Format: int64 */
            duration?: number | null;
            guid: string;
            itemType: string;
            requestedResolution?: string | null;
            requestedSeasons?: number[] | null;
            thumb?: string | null;
            title: string;
            /** Format: int32 */
            year?: number | null;
        };
        MediaVersion: {
            subtitles: string[];
            videoResolution: string;
        };
        Part: {
            Stream?: components["schemas"]["Stream"][];
            /** Format: int64 */
            id: number;
        };
        /** @description Single bonus feature/extra from the database */
        PlexExtra: {
            /** @description Plex extra type (e.g. "trailer", "behindTheScenes", "deleted_scene") */
            extraType?: string | null;
            key: string;
            ratingKey?: string | null;
            thumb?: string | null;
            title: string;
        };
        /** @description Query params for listing media requests */
        RequestsQuery: {
            /** @description "createdAt" (default) or "fulfilledAt" */
            sortBy?: string | null;
            /** @description "asc" or "desc" (default "desc") */
            sortOrder?: string | null;
            /** @description Filter: "pending", "fulfilled", or omit for all */
            status?: string | null;
        };
        SearchQuery: {
            /** Format: int32 */
            limit?: number | null;
            /** Format: int32 */
            offset?: number | null;
            q: string;
        };
        SearchResult: {
            contentRating?: string | null;
            /** Format: int64 */
            duration?: number | null;
            guid?: string | null;
            itemType: string;
            originallyAvailableAt?: string | null;
            /** Format: float */
            rank?: number | null;
            ratingKey: string;
            serverId: string;
            serverName: string;
            summary?: string | null;
            thumbPath?: string | null;
            title: string;
            /** Format: int32 */
            year?: number | null;
        };
        SearchResultsPage: {
            items: components["schemas"]["SearchResult"][];
            /** Format: int64 */
            limit: number;
            /** Format: int64 */
            offset: number;
            /** Format: int64 */
            total: number;
        };
        SeasonSummary: {
            artPath?: string | null;
            /** Format: int32 */
            episodeCount?: number | null;
            id: string;
            summary?: string | null;
            thumbPath?: string | null;
            title: string;
        };
        ServerAvailability: {
            accessToken: string;
            ratingKey: string;
            serverId: string;
            serverName: string;
            versions: components["schemas"]["MediaVersion"][];
        };
        Stream: {
            format?: string | null;
            /** Format: int64 */
            id: number;
            language?: string | null;
            language_code?: string | null;
            /** Format: int32 */
            streamType: number;
        };
        /** @description Information about the database and sync status. */
        SystemInfo: {
            /** @description Last sync error message if any. */
            lastError?: string | null;
            lastUpdated?: string | null;
            /** Format: int64 */
            offlineServers: number;
            /** Format: int64 */
            onlineServers: number;
            /** @description Whether a sync is currently in progress. */
            syncInProgress: boolean;
            /** Format: int64 */
            syncIntervalMinutes: number;
            /** Format: int64 */
            totalMovies: number;
            /** Format: int64 */
            totalShows: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    discover_handler: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
                /** @description Max results to return */
                limit?: number | null;
                /** @description Result offset (for pagination/infinite scroll) */
                offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated discover results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverResultsPage"];
                };
            };
        };
    };
    get_media_details_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Media GUID (e.g. plex://movie/...) */
                guid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Media details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaDetails"];
                };
            };
            /** @description Media not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_all_requests_handler: {
        parameters: {
            query?: {
                /** @description Filter: pending | fulfilled */
                status?: string | null;
                /** @description createdAt (default) | fulfilledAt */
                sortBy?: string | null;
                /** @description asc | desc (default desc) */
                sortOrder?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of requests */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaRequest"][];
                };
            };
        };
    };
    create_request_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaRequestPayload"];
            };
        };
        responses: {
            /** @description Created or updated requests */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaRequest"][];
                };
            };
        };
    };
    get_active_requests_by_guid_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Media GUID (full or normalized) */
                guid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of active requests for this media */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaRequest"][];
                };
            };
        };
    };
    delete_request_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Request ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not subscribed */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    search_handler: {
        parameters: {
            query: {
                /** @description Search terms (full-text; multiple words supported) */
                q: string;
                /** @description Max results to return */
                limit?: number | null;
                /** @description Result offset (for pagination/infinite scroll) */
                offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResultsPage"];
                };
            };
        };
    };
    get_servers_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of servers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DbServer"][];
                };
            };
        };
    };
    get_image_handler: {
        parameters: {
            query?: {
                /** @description Optional width in pixels for transcoded image */
                width?: number | null;
                /** @description Optional height in pixels for transcoded image */
                height?: number | null;
            };
            header?: never;
            path: {
                /** @description Server ID (Plex client identifier) */
                server_id: string;
                /** @description Image path (may contain slashes, e.g. library/metadata/123/thumb/456) */
                image_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image binary (JPEG) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_item_details_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server ID (Plex client identifier) */
                server_id: string;
                /** @description Plex rating key of the item (e.g. from list/children) */
                rating_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemWithDetails"];
                };
            };
            /** @description Server or item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_item_children_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server ID (Plex client identifier) */
                server_id: string;
                /** @description Plex rating key of the parent (show or season) */
                rating_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of child items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemList"];
                };
            };
            /** @description Server not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_item_extras_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server ID (Plex client identifier) */
                server_id: string;
                /** @description Plex rating key of the parent movie/show/season/episode */
                rating_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of extras */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlexExtra"][];
                };
            };
            /** @description Server not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_libraries_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server ID (Plex client identifier) */
                server_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of libraries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Library"][];
                };
            };
            /** @description Server not found in catalog */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_library_items_handler: {
        parameters: {
            query?: {
                /** @description Max results to return */
                limit?: number | null;
                /** @description Result offset (for pagination/infinite scroll) */
                offset?: number | null;
            };
            header?: never;
            path: {
                /** @description Server ID (Plex client identifier) */
                server_id: string;
                /** @description Library section key from /libraries */
                library_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated library items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryItemsPage"];
                };
            };
            /** @description Server not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_episodes_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server ID (Plex client identifier) */
                server_id: string;
                /** @description Season rating key, or show rating key if show has no seasons */
                season_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of episodes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeDetails"][];
                };
            };
            /** @description Server or season not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_seasons_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server ID (Plex client identifier) */
                server_id: string;
                /** @description Show rating key (from library items or children) */
                show_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of seasons */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonSummary"][];
                };
            };
            /** @description Server or show not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_system_info_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfo"];
                };
            };
        };
    };
}
